USE n7492_gsxr;

CREATE TABLE IF NOT EXISTS `BALADE` (
	`ID_BALADE` INT(4) AUTO_INCREMENT NOT NULL,
	`NOM_BALADE` VARCHAR(50) NOT NULL,
	`DATE_DEPART` DATETIME NOT NULL,
	`LIEU_RDV` VARCHAR(50) NOT NULL,
	KEY `index_balade` (`ID_BALADE`) USING BTREE,
	PRIMARY KEY (`ID_BALADE`)
) ENGINE=InnoDB;